version: '3'
services:
  web:
    build: ./app  # Set the build context to /app
    ports:
      - "8081:80"  # Expose port 80 within the container, map to 8081 on the host
    depends_on:
      - db
  web2:
    build: ./app  # Set the build context to /app
    ports:
      - "8082:80"  # Expose port 80 within the container, map to 8082 on the host
    depends_on:
      - db
  lb:
    build: ./balance
    ports:
      - "8080:80"  # Expose port 80 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount your nginx.conf file
    depends_on:
      - web
      - web2
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  shop_network:
    driver: bridge